INSERT INTO public."Provinces" (id, name, country_id, "createdAt", "updatedAt") VALUES
  (1,'Azua',63,NOW(),NOW()),
  (2,'Bahoruco',63,NOW(),NOW()),
  (3,'Barahona',63,NOW(),NOW()),
  (4,'Dajabón',63,NOW(),NOW()),
  (5,'Distrito Nacional',63,NOW(),NOW()),
  (6,'Duarte',63,NOW(),NOW()),
  (7,'El Seibo',63,NOW(),NOW()),
  (8,'Elías Piña',63,NOW(),NOW()),
  (9,'Espaillat',63,NOW(),NOW()),
  (10,'Hato Mayor',63,NOW(),NOW()),
  (11,'Hermanas Mirabal',63,NOW(),NOW()),
  (12,'Independencia',63,NOW(),NOW()),
  (13,'La Altagracia',63,NOW(),NOW()),
  (14,'La Romana',63,NOW(),NOW()),
  (15,'La Vega',63,NOW(),NOW()),
  (16,'María Trinidad Sánchez',63,NOW(),NOW()),
  (17,'Monseñor Nouel',63,NOW(),NOW()),
  (18,'Monte Cristi',63,NOW(),NOW()),
  (19,'Monte Plata',63,NOW(),NOW()),
  (20,'Pedernales',63,NOW(),NOW()),
  (21,'Peravia',63,NOW(),NOW()),
  (22,'Puerto Plata',63,NOW(),NOW()),
  (23,'Samaná',63,NOW(),NOW()),
  (24,'San Cristóbal',63,NOW(),NOW()),
  (25,'San José de Ocoa',63,NOW(),NOW()),
  (26,'San Juan',63,NOW(),NOW()),
  (27,'San Pedro de Macorís',63,NOW(),NOW()),
  (28,'Sánchez Ramirez',63,NOW(),NOW()),
  (29,'Santiago',63,NOW(),NOW()),
  (30,'Santiago Rodríguez',63,NOW(),NOW()),
  (31,'Santo Domingo',63,NOW(),NOW()),
  (32,'Valverde',63,NOW(),NOW());
